env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - XCPROJ="-workspace SwiftElm.xcworkspace -scheme SwiftElm"

before_install:
  # - brew update # Comment-Out: Too slow
  - brew install sourcery
  - sourcery --version

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build -destination 'platform=iOS Simulator,name=iPhone XS' ENABLE_TESTABILITY=YES $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-iOS
